{% set name = "winpty" %}
{% set version = "0.4.3" %}
{% set hash = "093037c39f9c899d79b74d5e15ff74fb59a98c492c5ed621e97e1090c3442865" %}

package:
  name: {{ name }}
  version: {{ version }}

source:
  fn: {{ name }}-{{ version }}.tar.gz
  url: https://github.com/rprichard/{{ name }}/archive/{{ version }}.tar.gz
  sha256: {{ hash }}
  patches:
     - 0001-disable-msys-compiler-check.patch

build:
  number: 3
  skip: True  # [not win]

requirements:
  build:
    - posix
    - m2w64-toolchain
    - git
    - curl
    - python
    - cmake
    - vc 14
  run:
    - vs2015_runtime

test:
  commands:
    - winpty-agent --version

about:
  home: https://github.com/rprichard/winpty
  license: MIT
  summary: |
    Winpty provides an interface similar to a Unix pty-master for communicating
    with Windows console programs.
  description: |
    Winpty is a Windows software package providing an interface similar to a Unix
    pty-master for communicating with Windows console programs. The package
    consists of a library (libwinpty) and a tool for Cygwin and MSYS for running
    Windows console programs in a Cygwin/MSYS pty.
  doc_url: https://github.com/rprichard/winpty
  dev_url: https://github.com/rprichard/winpty

extra:
  recipe-maintainers:
    - blink1073
    - ccordoba12
    - andfoy
