travis:
  secure:
    BINSTAR_TOKEN: FzweDgwbtmnGcYp4/R5XqnRksh1lfH4cQ/T7+i7eWkxa0YtwKj0j7KKQt3vijx//5w0kOA7g7dhyjqAoTea3BPCx3tDiPx5q9DNNTCBfhpw+RiAn9GJvry6s19p4eoTYtmPFm17cD0LrdATgcWJU/nhLapN6gLaTw4hm1qffLrsFGTXsMhjlnXOY6/MMFtBWblP/F95BDa/i7o9BfaBx7Z/SP7u3IHwivqGaHpmHJ2l3IPuc944sKQpHI8L8tlehigeU86ThXs5OGTC6GeCQ9GukuENpLgKZAXpDHMbx4gWI4KMvvyw1LrnU8FZYW1z/xtXzBB8huK4zgHZA5qMVBGS/x/pCj/z5ZG7VhHNCYAs+XaFgGk5tmy/r3hC6j8izkx2oNCAikuzyn+x7sU6ZDpo6V4PHyasl2sUEsJHK2qC/UwNDv6evxxSzKkqaxMlKD5RFV5uZ9xx/+YoOcRGMUJkkvxtpHU4dJw9eh80MOQPLLpj+PCskzL3Ve70jW/pb070rOXuBmbHmRTZMtbNnoO7pWSw5CyzHIbHZMXOToBBK37a6MEShejDsA89d0o9EdsO1sCkdhDV5izUrkwmTvu8OtbEhuFUKUZtJ1o9tr102UJg6Pb52926/jZYSX6SgQuO9QDUKSEm+VxV1dEV0BYWqPiJWOzqM2z76gnToDrI=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
